spring:
  datasource:
    url: jdbc:h2:mem:maindb
    username: SA
    password:
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8090
